// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDnVhu-KVrD7CmTC0pt764WFpVwA3iIA8',
    appId: '1:616730025284:web:54c4dc9cdcbeedf3b78b11',
    messagingSenderId: '616730025284',
    projectId: 'project2-b5fe6',
    authDomain: 'project2-b5fe6.firebaseapp.com',
    storageBucket: 'project2-b5fe6.appspot.com',
    measurementId: 'G-J8F9NW8J7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR8ePyWup2pVvuruWt32pR_Z58tYZH15c',
    appId: '1:616730025284:android:c454b1b689f3da8ab78b11',
    messagingSenderId: '616730025284',
    projectId: 'project2-b5fe6',
    storageBucket: 'project2-b5fe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNfrbsiTgbybTlCdDiRax6SpX7RW_d700',
    appId: '1:616730025284:ios:3ff6be61c648dcf6b78b11',
    messagingSenderId: '616730025284',
    projectId: 'project2-b5fe6',
    storageBucket: 'project2-b5fe6.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNfrbsiTgbybTlCdDiRax6SpX7RW_d700',
    appId: '1:616730025284:ios:3ff6be61c648dcf6b78b11',
    messagingSenderId: '616730025284',
    projectId: 'project2-b5fe6',
    storageBucket: 'project2-b5fe6.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDnVhu-KVrD7CmTC0pt764WFpVwA3iIA8',
    appId: '1:616730025284:web:ee58cc238993daf3b78b11',
    messagingSenderId: '616730025284',
    projectId: 'project2-b5fe6',
    authDomain: 'project2-b5fe6.firebaseapp.com',
    storageBucket: 'project2-b5fe6.appspot.com',
    measurementId: 'G-0BW21FLKZE',
  );
}
